/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author LENOVO
 */
public class ChessGameBoard extends javax.swing.JFrame {

    /**
     * Creates new form ChessGameBoard
     */
    public ChessGameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p5 = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        p6 = new javax.swing.JPanel();
        p8 = new javax.swing.JPanel();
        p7 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        p9 = new javax.swing.JPanel();
        p10 = new javax.swing.JPanel();
        p11 = new javax.swing.JPanel();
        p12 = new javax.swing.JPanel();
        p13 = new javax.swing.JPanel();
        p14 = new javax.swing.JPanel();
        p15 = new javax.swing.JPanel();
        p16 = new javax.swing.JPanel();
        p21 = new javax.swing.JPanel();
        p22 = new javax.swing.JPanel();
        p24 = new javax.swing.JPanel();
        p23 = new javax.swing.JPanel();
        p20 = new javax.swing.JPanel();
        p19 = new javax.swing.JPanel();
        p18 = new javax.swing.JPanel();
        p17 = new javax.swing.JPanel();
        p26 = new javax.swing.JPanel();
        p27 = new javax.swing.JPanel();
        p28 = new javax.swing.JPanel();
        p29 = new javax.swing.JPanel();
        p30 = new javax.swing.JPanel();
        p31 = new javax.swing.JPanel();
        p32 = new javax.swing.JPanel();
        p25 = new javax.swing.JPanel();
        p37 = new javax.swing.JPanel();
        p38 = new javax.swing.JPanel();
        p40 = new javax.swing.JPanel();
        p39 = new javax.swing.JPanel();
        p36 = new javax.swing.JPanel();
        p35 = new javax.swing.JPanel();
        p34 = new javax.swing.JPanel();
        p33 = new javax.swing.JPanel();
        p42 = new javax.swing.JPanel();
        p43 = new javax.swing.JPanel();
        p44 = new javax.swing.JPanel();
        p45 = new javax.swing.JPanel();
        p46 = new javax.swing.JPanel();
        p47 = new javax.swing.JPanel();
        p48 = new javax.swing.JPanel();
        p41 = new javax.swing.JPanel();
        p53 = new javax.swing.JPanel();
        p54 = new javax.swing.JPanel();
        p56 = new javax.swing.JPanel();
        p55 = new javax.swing.JPanel();
        p52 = new javax.swing.JPanel();
        p51 = new javax.swing.JPanel();
        p50 = new javax.swing.JPanel();
        p49 = new javax.swing.JPanel();
        p58 = new javax.swing.JPanel();
        p59 = new javax.swing.JPanel();
        p60 = new javax.swing.JPanel();
        p61 = new javax.swing.JPanel();
        p62 = new javax.swing.JPanel();
        p63 = new javax.swing.JPanel();
        p64 = new javax.swing.JPanel();
        p57 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        p5.setBackground(new java.awt.Color(255, 228, 178));
        p5.setAlignmentX(0.0F);
        p5.setAlignmentY(0.0F);
        p5.setEnabled(false);
        p5.setFocusable(false);
        p5.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p2.setBackground(new java.awt.Color(151, 119, 84));
        p2.setAlignmentX(0.0F);
        p2.setAlignmentY(0.0F);
        p2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p2.setEnabled(false);
        p2.setFocusable(false);
        p2.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p6.setBackground(new java.awt.Color(151, 119, 84));
        p6.setAlignmentX(0.0F);
        p6.setAlignmentY(0.0F);
        p6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p6.setEnabled(false);
        p6.setFocusable(false);
        p6.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p8.setBackground(new java.awt.Color(151, 119, 84));
        p8.setAlignmentX(0.0F);
        p8.setAlignmentY(0.0F);
        p8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p8.setEnabled(false);
        p8.setFocusable(false);
        p8.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p7.setBackground(new java.awt.Color(255, 228, 178));
        p7.setAlignmentX(0.0F);
        p7.setAlignmentY(0.0F);
        p7.setEnabled(false);
        p7.setFocusable(false);
        p7.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p4.setBackground(new java.awt.Color(151, 119, 84));
        p4.setAlignmentX(0.0F);
        p4.setAlignmentY(0.0F);
        p4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p4.setEnabled(false);
        p4.setFocusable(false);
        p4.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p3.setBackground(new java.awt.Color(255, 228, 178));
        p3.setAlignmentX(0.0F);
        p3.setAlignmentY(0.0F);
        p3.setEnabled(false);
        p3.setFocusable(false);
        p3.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p1.setBackground(new java.awt.Color(255, 228, 178));
        p1.setAlignmentX(0.0F);
        p1.setAlignmentY(0.0F);
        p1.setEnabled(false);
        p1.setFocusable(false);
        p1.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p9.setBackground(new java.awt.Color(151, 119, 84));
        p9.setAlignmentX(0.0F);
        p9.setAlignmentY(0.0F);
        p9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p9.setEnabled(false);
        p9.setFocusable(false);
        p9.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p9Layout = new javax.swing.GroupLayout(p9);
        p9.setLayout(p9Layout);
        p9Layout.setHorizontalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p9Layout.setVerticalGroup(
            p9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p10.setBackground(new java.awt.Color(255, 228, 178));
        p10.setAlignmentX(0.0F);
        p10.setAlignmentY(0.0F);
        p10.setEnabled(false);
        p10.setFocusable(false);
        p10.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p10Layout = new javax.swing.GroupLayout(p10);
        p10.setLayout(p10Layout);
        p10Layout.setHorizontalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p10Layout.setVerticalGroup(
            p10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p11.setBackground(new java.awt.Color(151, 119, 84));
        p11.setAlignmentX(0.0F);
        p11.setAlignmentY(0.0F);
        p11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p11.setEnabled(false);
        p11.setFocusable(false);
        p11.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p12.setBackground(new java.awt.Color(255, 228, 178));
        p12.setAlignmentX(0.0F);
        p12.setAlignmentY(0.0F);
        p12.setEnabled(false);
        p12.setFocusable(false);
        p12.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p12Layout = new javax.swing.GroupLayout(p12);
        p12.setLayout(p12Layout);
        p12Layout.setHorizontalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p12Layout.setVerticalGroup(
            p12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p13.setBackground(new java.awt.Color(151, 119, 84));
        p13.setAlignmentX(0.0F);
        p13.setAlignmentY(0.0F);
        p13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p13.setEnabled(false);
        p13.setFocusable(false);
        p13.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p13Layout = new javax.swing.GroupLayout(p13);
        p13.setLayout(p13Layout);
        p13Layout.setHorizontalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p13Layout.setVerticalGroup(
            p13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p14.setBackground(new java.awt.Color(255, 228, 178));
        p14.setAlignmentX(0.0F);
        p14.setAlignmentY(0.0F);
        p14.setEnabled(false);
        p14.setFocusable(false);
        p14.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p14Layout = new javax.swing.GroupLayout(p14);
        p14.setLayout(p14Layout);
        p14Layout.setHorizontalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p14Layout.setVerticalGroup(
            p14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p15.setBackground(new java.awt.Color(151, 119, 84));
        p15.setAlignmentX(0.0F);
        p15.setAlignmentY(0.0F);
        p15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p15.setEnabled(false);
        p15.setFocusable(false);
        p15.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p15Layout = new javax.swing.GroupLayout(p15);
        p15.setLayout(p15Layout);
        p15Layout.setHorizontalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p15Layout.setVerticalGroup(
            p15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p16.setBackground(new java.awt.Color(255, 228, 178));
        p16.setAlignmentX(0.0F);
        p16.setAlignmentY(0.0F);
        p16.setEnabled(false);
        p16.setFocusable(false);
        p16.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p16Layout = new javax.swing.GroupLayout(p16);
        p16.setLayout(p16Layout);
        p16Layout.setHorizontalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p16Layout.setVerticalGroup(
            p16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p21.setBackground(new java.awt.Color(255, 228, 178));
        p21.setAlignmentX(0.0F);
        p21.setAlignmentY(0.0F);
        p21.setEnabled(false);
        p21.setFocusable(false);
        p21.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p21Layout = new javax.swing.GroupLayout(p21);
        p21.setLayout(p21Layout);
        p21Layout.setHorizontalGroup(
            p21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p21Layout.setVerticalGroup(
            p21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p22.setBackground(new java.awt.Color(151, 119, 84));
        p22.setAlignmentX(0.0F);
        p22.setAlignmentY(0.0F);
        p22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p22.setEnabled(false);
        p22.setFocusable(false);
        p22.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p22Layout = new javax.swing.GroupLayout(p22);
        p22.setLayout(p22Layout);
        p22Layout.setHorizontalGroup(
            p22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p22Layout.setVerticalGroup(
            p22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p24.setBackground(new java.awt.Color(151, 119, 84));
        p24.setAlignmentX(0.0F);
        p24.setAlignmentY(0.0F);
        p24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p24.setEnabled(false);
        p24.setFocusable(false);
        p24.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p24Layout = new javax.swing.GroupLayout(p24);
        p24.setLayout(p24Layout);
        p24Layout.setHorizontalGroup(
            p24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p24Layout.setVerticalGroup(
            p24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p23.setBackground(new java.awt.Color(255, 228, 178));
        p23.setAlignmentX(0.0F);
        p23.setAlignmentY(0.0F);
        p23.setEnabled(false);
        p23.setFocusable(false);
        p23.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p23Layout = new javax.swing.GroupLayout(p23);
        p23.setLayout(p23Layout);
        p23Layout.setHorizontalGroup(
            p23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p23Layout.setVerticalGroup(
            p23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p20.setBackground(new java.awt.Color(151, 119, 84));
        p20.setAlignmentX(0.0F);
        p20.setAlignmentY(0.0F);
        p20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p20.setEnabled(false);
        p20.setFocusable(false);
        p20.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p20Layout = new javax.swing.GroupLayout(p20);
        p20.setLayout(p20Layout);
        p20Layout.setHorizontalGroup(
            p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p20Layout.setVerticalGroup(
            p20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p19.setBackground(new java.awt.Color(255, 228, 178));
        p19.setAlignmentX(0.0F);
        p19.setAlignmentY(0.0F);
        p19.setEnabled(false);
        p19.setFocusable(false);
        p19.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p19Layout = new javax.swing.GroupLayout(p19);
        p19.setLayout(p19Layout);
        p19Layout.setHorizontalGroup(
            p19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p19Layout.setVerticalGroup(
            p19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p18.setBackground(new java.awt.Color(151, 119, 84));
        p18.setAlignmentX(0.0F);
        p18.setAlignmentY(0.0F);
        p18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p18.setEnabled(false);
        p18.setFocusable(false);
        p18.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p18Layout = new javax.swing.GroupLayout(p18);
        p18.setLayout(p18Layout);
        p18Layout.setHorizontalGroup(
            p18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p18Layout.setVerticalGroup(
            p18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p17.setBackground(new java.awt.Color(255, 228, 178));
        p17.setAlignmentX(0.0F);
        p17.setAlignmentY(0.0F);
        p17.setEnabled(false);
        p17.setFocusable(false);
        p17.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p17Layout = new javax.swing.GroupLayout(p17);
        p17.setLayout(p17Layout);
        p17Layout.setHorizontalGroup(
            p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p17Layout.setVerticalGroup(
            p17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p26.setBackground(new java.awt.Color(255, 228, 178));
        p26.setAlignmentX(0.0F);
        p26.setAlignmentY(0.0F);
        p26.setEnabled(false);
        p26.setFocusable(false);
        p26.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p26Layout = new javax.swing.GroupLayout(p26);
        p26.setLayout(p26Layout);
        p26Layout.setHorizontalGroup(
            p26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p26Layout.setVerticalGroup(
            p26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p27.setBackground(new java.awt.Color(151, 119, 84));
        p27.setAlignmentX(0.0F);
        p27.setAlignmentY(0.0F);
        p27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p27.setEnabled(false);
        p27.setFocusable(false);
        p27.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p27Layout = new javax.swing.GroupLayout(p27);
        p27.setLayout(p27Layout);
        p27Layout.setHorizontalGroup(
            p27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p27Layout.setVerticalGroup(
            p27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p28.setBackground(new java.awt.Color(255, 228, 178));
        p28.setAlignmentX(0.0F);
        p28.setAlignmentY(0.0F);
        p28.setEnabled(false);
        p28.setFocusable(false);
        p28.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p28Layout = new javax.swing.GroupLayout(p28);
        p28.setLayout(p28Layout);
        p28Layout.setHorizontalGroup(
            p28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p28Layout.setVerticalGroup(
            p28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p29.setBackground(new java.awt.Color(151, 119, 84));
        p29.setAlignmentX(0.0F);
        p29.setAlignmentY(0.0F);
        p29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p29.setEnabled(false);
        p29.setFocusable(false);
        p29.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p29Layout = new javax.swing.GroupLayout(p29);
        p29.setLayout(p29Layout);
        p29Layout.setHorizontalGroup(
            p29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p29Layout.setVerticalGroup(
            p29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p30.setBackground(new java.awt.Color(255, 228, 178));
        p30.setAlignmentX(0.0F);
        p30.setAlignmentY(0.0F);
        p30.setEnabled(false);
        p30.setFocusable(false);
        p30.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p30Layout = new javax.swing.GroupLayout(p30);
        p30.setLayout(p30Layout);
        p30Layout.setHorizontalGroup(
            p30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p30Layout.setVerticalGroup(
            p30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p31.setBackground(new java.awt.Color(151, 119, 84));
        p31.setAlignmentX(0.0F);
        p31.setAlignmentY(0.0F);
        p31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p31.setEnabled(false);
        p31.setFocusable(false);
        p31.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p31Layout = new javax.swing.GroupLayout(p31);
        p31.setLayout(p31Layout);
        p31Layout.setHorizontalGroup(
            p31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p31Layout.setVerticalGroup(
            p31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p32.setBackground(new java.awt.Color(255, 228, 178));
        p32.setAlignmentX(0.0F);
        p32.setAlignmentY(0.0F);
        p32.setEnabled(false);
        p32.setFocusable(false);
        p32.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p32Layout = new javax.swing.GroupLayout(p32);
        p32.setLayout(p32Layout);
        p32Layout.setHorizontalGroup(
            p32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p32Layout.setVerticalGroup(
            p32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p25.setBackground(new java.awt.Color(151, 119, 84));
        p25.setAlignmentX(0.0F);
        p25.setAlignmentY(0.0F);
        p25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p25.setEnabled(false);
        p25.setFocusable(false);
        p25.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p25Layout = new javax.swing.GroupLayout(p25);
        p25.setLayout(p25Layout);
        p25Layout.setHorizontalGroup(
            p25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p25Layout.setVerticalGroup(
            p25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p37.setBackground(new java.awt.Color(255, 228, 178));
        p37.setAlignmentX(0.0F);
        p37.setAlignmentY(0.0F);
        p37.setEnabled(false);
        p37.setFocusable(false);
        p37.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p37Layout = new javax.swing.GroupLayout(p37);
        p37.setLayout(p37Layout);
        p37Layout.setHorizontalGroup(
            p37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p37Layout.setVerticalGroup(
            p37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p38.setBackground(new java.awt.Color(151, 119, 84));
        p38.setAlignmentX(0.0F);
        p38.setAlignmentY(0.0F);
        p38.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p38.setEnabled(false);
        p38.setFocusable(false);
        p38.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p38Layout = new javax.swing.GroupLayout(p38);
        p38.setLayout(p38Layout);
        p38Layout.setHorizontalGroup(
            p38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p38Layout.setVerticalGroup(
            p38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p40.setBackground(new java.awt.Color(151, 119, 84));
        p40.setAlignmentX(0.0F);
        p40.setAlignmentY(0.0F);
        p40.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p40.setEnabled(false);
        p40.setFocusable(false);
        p40.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p40Layout = new javax.swing.GroupLayout(p40);
        p40.setLayout(p40Layout);
        p40Layout.setHorizontalGroup(
            p40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p40Layout.setVerticalGroup(
            p40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p39.setBackground(new java.awt.Color(255, 228, 178));
        p39.setAlignmentX(0.0F);
        p39.setAlignmentY(0.0F);
        p39.setEnabled(false);
        p39.setFocusable(false);
        p39.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p39Layout = new javax.swing.GroupLayout(p39);
        p39.setLayout(p39Layout);
        p39Layout.setHorizontalGroup(
            p39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p39Layout.setVerticalGroup(
            p39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p36.setBackground(new java.awt.Color(151, 119, 84));
        p36.setAlignmentX(0.0F);
        p36.setAlignmentY(0.0F);
        p36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p36.setEnabled(false);
        p36.setFocusable(false);
        p36.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p36Layout = new javax.swing.GroupLayout(p36);
        p36.setLayout(p36Layout);
        p36Layout.setHorizontalGroup(
            p36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p36Layout.setVerticalGroup(
            p36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p35.setBackground(new java.awt.Color(255, 228, 178));
        p35.setAlignmentX(0.0F);
        p35.setAlignmentY(0.0F);
        p35.setEnabled(false);
        p35.setFocusable(false);
        p35.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p35Layout = new javax.swing.GroupLayout(p35);
        p35.setLayout(p35Layout);
        p35Layout.setHorizontalGroup(
            p35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p35Layout.setVerticalGroup(
            p35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p34.setBackground(new java.awt.Color(151, 119, 84));
        p34.setAlignmentX(0.0F);
        p34.setAlignmentY(0.0F);
        p34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p34.setEnabled(false);
        p34.setFocusable(false);
        p34.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p34Layout = new javax.swing.GroupLayout(p34);
        p34.setLayout(p34Layout);
        p34Layout.setHorizontalGroup(
            p34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p34Layout.setVerticalGroup(
            p34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p33.setBackground(new java.awt.Color(255, 228, 178));
        p33.setAlignmentX(0.0F);
        p33.setAlignmentY(0.0F);
        p33.setEnabled(false);
        p33.setFocusable(false);
        p33.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p33Layout = new javax.swing.GroupLayout(p33);
        p33.setLayout(p33Layout);
        p33Layout.setHorizontalGroup(
            p33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p33Layout.setVerticalGroup(
            p33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p42.setBackground(new java.awt.Color(255, 228, 178));
        p42.setAlignmentX(0.0F);
        p42.setAlignmentY(0.0F);
        p42.setEnabled(false);
        p42.setFocusable(false);
        p42.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p42Layout = new javax.swing.GroupLayout(p42);
        p42.setLayout(p42Layout);
        p42Layout.setHorizontalGroup(
            p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p42Layout.setVerticalGroup(
            p42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p43.setBackground(new java.awt.Color(151, 119, 84));
        p43.setAlignmentX(0.0F);
        p43.setAlignmentY(0.0F);
        p43.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p43.setEnabled(false);
        p43.setFocusable(false);
        p43.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p43Layout = new javax.swing.GroupLayout(p43);
        p43.setLayout(p43Layout);
        p43Layout.setHorizontalGroup(
            p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p43Layout.setVerticalGroup(
            p43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p44.setBackground(new java.awt.Color(255, 228, 178));
        p44.setAlignmentX(0.0F);
        p44.setAlignmentY(0.0F);
        p44.setEnabled(false);
        p44.setFocusable(false);
        p44.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p44Layout = new javax.swing.GroupLayout(p44);
        p44.setLayout(p44Layout);
        p44Layout.setHorizontalGroup(
            p44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p44Layout.setVerticalGroup(
            p44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p45.setBackground(new java.awt.Color(151, 119, 84));
        p45.setAlignmentX(0.0F);
        p45.setAlignmentY(0.0F);
        p45.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p45.setEnabled(false);
        p45.setFocusable(false);
        p45.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p45Layout = new javax.swing.GroupLayout(p45);
        p45.setLayout(p45Layout);
        p45Layout.setHorizontalGroup(
            p45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p45Layout.setVerticalGroup(
            p45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p46.setBackground(new java.awt.Color(255, 228, 178));
        p46.setAlignmentX(0.0F);
        p46.setAlignmentY(0.0F);
        p46.setEnabled(false);
        p46.setFocusable(false);
        p46.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p46Layout = new javax.swing.GroupLayout(p46);
        p46.setLayout(p46Layout);
        p46Layout.setHorizontalGroup(
            p46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p46Layout.setVerticalGroup(
            p46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p47.setBackground(new java.awt.Color(151, 119, 84));
        p47.setAlignmentX(0.0F);
        p47.setAlignmentY(0.0F);
        p47.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p47.setEnabled(false);
        p47.setFocusable(false);
        p47.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p47Layout = new javax.swing.GroupLayout(p47);
        p47.setLayout(p47Layout);
        p47Layout.setHorizontalGroup(
            p47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p47Layout.setVerticalGroup(
            p47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p48.setBackground(new java.awt.Color(255, 228, 178));
        p48.setAlignmentX(0.0F);
        p48.setAlignmentY(0.0F);
        p48.setEnabled(false);
        p48.setFocusable(false);
        p48.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p48Layout = new javax.swing.GroupLayout(p48);
        p48.setLayout(p48Layout);
        p48Layout.setHorizontalGroup(
            p48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p48Layout.setVerticalGroup(
            p48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p41.setBackground(new java.awt.Color(151, 119, 84));
        p41.setAlignmentX(0.0F);
        p41.setAlignmentY(0.0F);
        p41.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p41.setEnabled(false);
        p41.setFocusable(false);
        p41.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p41Layout = new javax.swing.GroupLayout(p41);
        p41.setLayout(p41Layout);
        p41Layout.setHorizontalGroup(
            p41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p41Layout.setVerticalGroup(
            p41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p53.setBackground(new java.awt.Color(255, 228, 178));
        p53.setAlignmentX(0.0F);
        p53.setAlignmentY(0.0F);
        p53.setEnabled(false);
        p53.setFocusable(false);
        p53.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p53Layout = new javax.swing.GroupLayout(p53);
        p53.setLayout(p53Layout);
        p53Layout.setHorizontalGroup(
            p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p53Layout.setVerticalGroup(
            p53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p54.setBackground(new java.awt.Color(151, 119, 84));
        p54.setAlignmentX(0.0F);
        p54.setAlignmentY(0.0F);
        p54.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p54.setEnabled(false);
        p54.setFocusable(false);
        p54.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p54Layout = new javax.swing.GroupLayout(p54);
        p54.setLayout(p54Layout);
        p54Layout.setHorizontalGroup(
            p54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p54Layout.setVerticalGroup(
            p54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p56.setBackground(new java.awt.Color(151, 119, 84));
        p56.setAlignmentX(0.0F);
        p56.setAlignmentY(0.0F);
        p56.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p56.setEnabled(false);
        p56.setFocusable(false);
        p56.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p56Layout = new javax.swing.GroupLayout(p56);
        p56.setLayout(p56Layout);
        p56Layout.setHorizontalGroup(
            p56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p56Layout.setVerticalGroup(
            p56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p55.setBackground(new java.awt.Color(255, 228, 178));
        p55.setAlignmentX(0.0F);
        p55.setAlignmentY(0.0F);
        p55.setEnabled(false);
        p55.setFocusable(false);
        p55.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p55Layout = new javax.swing.GroupLayout(p55);
        p55.setLayout(p55Layout);
        p55Layout.setHorizontalGroup(
            p55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p55Layout.setVerticalGroup(
            p55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p52.setBackground(new java.awt.Color(151, 119, 84));
        p52.setAlignmentX(0.0F);
        p52.setAlignmentY(0.0F);
        p52.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p52.setEnabled(false);
        p52.setFocusable(false);
        p52.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p52Layout = new javax.swing.GroupLayout(p52);
        p52.setLayout(p52Layout);
        p52Layout.setHorizontalGroup(
            p52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p52Layout.setVerticalGroup(
            p52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p51.setBackground(new java.awt.Color(255, 228, 178));
        p51.setAlignmentX(0.0F);
        p51.setAlignmentY(0.0F);
        p51.setEnabled(false);
        p51.setFocusable(false);
        p51.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p51Layout = new javax.swing.GroupLayout(p51);
        p51.setLayout(p51Layout);
        p51Layout.setHorizontalGroup(
            p51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p51Layout.setVerticalGroup(
            p51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p50.setBackground(new java.awt.Color(151, 119, 84));
        p50.setAlignmentX(0.0F);
        p50.setAlignmentY(0.0F);
        p50.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p50.setEnabled(false);
        p50.setFocusable(false);
        p50.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p50Layout = new javax.swing.GroupLayout(p50);
        p50.setLayout(p50Layout);
        p50Layout.setHorizontalGroup(
            p50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p50Layout.setVerticalGroup(
            p50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p49.setBackground(new java.awt.Color(255, 228, 178));
        p49.setAlignmentX(0.0F);
        p49.setAlignmentY(0.0F);
        p49.setEnabled(false);
        p49.setFocusable(false);
        p49.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p49Layout = new javax.swing.GroupLayout(p49);
        p49.setLayout(p49Layout);
        p49Layout.setHorizontalGroup(
            p49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p49Layout.setVerticalGroup(
            p49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p58.setBackground(new java.awt.Color(255, 228, 178));
        p58.setAlignmentX(0.0F);
        p58.setAlignmentY(0.0F);
        p58.setEnabled(false);
        p58.setFocusable(false);
        p58.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p58Layout = new javax.swing.GroupLayout(p58);
        p58.setLayout(p58Layout);
        p58Layout.setHorizontalGroup(
            p58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p58Layout.setVerticalGroup(
            p58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p59.setBackground(new java.awt.Color(151, 119, 84));
        p59.setAlignmentX(0.0F);
        p59.setAlignmentY(0.0F);
        p59.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p59.setEnabled(false);
        p59.setFocusable(false);
        p59.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p59Layout = new javax.swing.GroupLayout(p59);
        p59.setLayout(p59Layout);
        p59Layout.setHorizontalGroup(
            p59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p59Layout.setVerticalGroup(
            p59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p60.setBackground(new java.awt.Color(255, 228, 178));
        p60.setAlignmentX(0.0F);
        p60.setAlignmentY(0.0F);
        p60.setEnabled(false);
        p60.setFocusable(false);
        p60.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p60Layout = new javax.swing.GroupLayout(p60);
        p60.setLayout(p60Layout);
        p60Layout.setHorizontalGroup(
            p60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p60Layout.setVerticalGroup(
            p60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p61.setBackground(new java.awt.Color(151, 119, 84));
        p61.setAlignmentX(0.0F);
        p61.setAlignmentY(0.0F);
        p61.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p61.setEnabled(false);
        p61.setFocusable(false);
        p61.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p61Layout = new javax.swing.GroupLayout(p61);
        p61.setLayout(p61Layout);
        p61Layout.setHorizontalGroup(
            p61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p61Layout.setVerticalGroup(
            p61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p62.setBackground(new java.awt.Color(255, 228, 178));
        p62.setAlignmentX(0.0F);
        p62.setAlignmentY(0.0F);
        p62.setEnabled(false);
        p62.setFocusable(false);
        p62.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p62Layout = new javax.swing.GroupLayout(p62);
        p62.setLayout(p62Layout);
        p62Layout.setHorizontalGroup(
            p62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p62Layout.setVerticalGroup(
            p62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p63.setBackground(new java.awt.Color(151, 119, 84));
        p63.setAlignmentX(0.0F);
        p63.setAlignmentY(0.0F);
        p63.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p63.setEnabled(false);
        p63.setFocusable(false);
        p63.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p63Layout = new javax.swing.GroupLayout(p63);
        p63.setLayout(p63Layout);
        p63Layout.setHorizontalGroup(
            p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p63Layout.setVerticalGroup(
            p63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p64.setBackground(new java.awt.Color(255, 228, 178));
        p64.setAlignmentX(0.0F);
        p64.setAlignmentY(0.0F);
        p64.setEnabled(false);
        p64.setFocusable(false);
        p64.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p64Layout = new javax.swing.GroupLayout(p64);
        p64.setLayout(p64Layout);
        p64Layout.setHorizontalGroup(
            p64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p64Layout.setVerticalGroup(
            p64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        p57.setBackground(new java.awt.Color(151, 119, 84));
        p57.setAlignmentX(0.0F);
        p57.setAlignmentY(0.0F);
        p57.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p57.setEnabled(false);
        p57.setFocusable(false);
        p57.setPreferredSize(new java.awt.Dimension(75, 75));

        javax.swing.GroupLayout p57Layout = new javax.swing.GroupLayout(p57);
        p57.setLayout(p57Layout);
        p57Layout.setHorizontalGroup(
            p57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        p57Layout.setVerticalGroup(
            p57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(p64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChessGameBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p10;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p12;
    private javax.swing.JPanel p13;
    private javax.swing.JPanel p14;
    private javax.swing.JPanel p15;
    private javax.swing.JPanel p16;
    private javax.swing.JPanel p17;
    private javax.swing.JPanel p18;
    private javax.swing.JPanel p19;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p20;
    private javax.swing.JPanel p21;
    private javax.swing.JPanel p22;
    private javax.swing.JPanel p23;
    private javax.swing.JPanel p24;
    private javax.swing.JPanel p25;
    private javax.swing.JPanel p26;
    private javax.swing.JPanel p27;
    private javax.swing.JPanel p28;
    private javax.swing.JPanel p29;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p30;
    private javax.swing.JPanel p31;
    private javax.swing.JPanel p32;
    private javax.swing.JPanel p33;
    private javax.swing.JPanel p34;
    private javax.swing.JPanel p35;
    private javax.swing.JPanel p36;
    private javax.swing.JPanel p37;
    private javax.swing.JPanel p38;
    private javax.swing.JPanel p39;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p40;
    private javax.swing.JPanel p41;
    private javax.swing.JPanel p42;
    private javax.swing.JPanel p43;
    private javax.swing.JPanel p44;
    private javax.swing.JPanel p45;
    private javax.swing.JPanel p46;
    private javax.swing.JPanel p47;
    private javax.swing.JPanel p48;
    private javax.swing.JPanel p49;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p50;
    private javax.swing.JPanel p51;
    private javax.swing.JPanel p52;
    private javax.swing.JPanel p53;
    private javax.swing.JPanel p54;
    private javax.swing.JPanel p55;
    private javax.swing.JPanel p56;
    private javax.swing.JPanel p57;
    private javax.swing.JPanel p58;
    private javax.swing.JPanel p59;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p60;
    private javax.swing.JPanel p61;
    private javax.swing.JPanel p62;
    private javax.swing.JPanel p63;
    private javax.swing.JPanel p64;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JPanel p9;
    // End of variables declaration//GEN-END:variables
}
